CLEARSCREEN.
SWITCH TO 0.
CD(LAUNCH).
CD(SR71).
PRINT "Pisa DIGITAL FLIGHT COMPUTER MODEL 3380".
PRINT "0".
PRINT "0".
PRINT "0".
PRINT "0".
PRINT "TAPE1 FOUND ON HEAD1".
PRINT "TYPE -RUN TAPE1- TO READ".
PRINT "0".
PRINT "0".
