CLEARSCREEN.
WAIT 1.
CD(PROGRAMS).
PRINT "".
PRINT "".
PRINT "".
PRINT "SR71 FLIGHT SOFTWARE V1.01".  
PRINT "PROGRAM LIST".
PRINT "".
PRINT "".
PRINT "1:MISSION_BRIEFING".
PRINT "2:FLIGHT_PROCEDURES".
PRINT "3:STAR_TRACKING".
PRINT "4:SETTING".
PRINT "5:CAMERA_SYSTEM".
PRINT "".
PRINT "".
PRINT "".
PRINT "".
PRINT "Pisa Flight Operation Softwares".
PRINT "".
PRINT "".